server:
  port: 8989
spring:
  application:
    name: poc-gateway
  cloud:
    config:
      label: main
      name: poc-gateway
      enabled: true
    refresh:
      enabled: true
    bus:
      enabled: true
      refresh:
        enabled: true
    stream:
      bindings:
        springCloudBusOutput:
          destination: poc-config-server-bus
          binder: rabbit
        springCloudBusInput:
          destination: poc-config-server-bus
          binder: rabbit
      default-binder: rabbit
  config:
    import: configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh